# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(upload_to=b'', validators=[webapp.validators.validate_file_extension]),
        ),
    ]
