# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='activity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='efficacy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='potency',
            field=models.IntegerField(default=0),
        ),
    ]
