library(data.table)
setwd("/home/tox2020/Desktop/HSE")
args = commandArgs(trailingOnly = TRUE)
dirname = args[1]

data1 <- fread(paste('media/',dirname,'/res.csv',sep=""), select = c("ATS3p",          "IC4",            "ATS3v",          "ATS2p",          "ATS4i",         
                                     "ATS4p",          "IC5",            "SpMAD_Dt",       "ATS2v",          "ATS5i",         
                                     "MPC10",          "MPC8",           "MPC9",           "TPC",            "JGI6",          
                                     "MWC7",           "ATS4v",          "ATS5p",          "MPC5",           "ATS3i",         
                                     "EE_Dt",          "SpAD_Dt",        "SpMax_Dt",       "MWC9",           "IC3",           
                                     "MWC3",           "SRW6",           "MPC4",           "MWC5",           "MWC6",          
                                     "SRW8",           "MPC3",           "nBondsS3",       "TIC3",           "fragC",         
                                     "MPC2",           "TIC1",           "TIC4",           "TIC5",           "ATSC4v",        
                                     "SRW4",           "ATS2i",          "SIC4",           "MWC2",           "Zagreb",        
                                     "nBondsS",        "nBondsS2",       "C3SP3",          "ATSC4i",         "CIC4",          
                                     "nFG12Ring",      "nFRing",         "nTG12Ring",      "nTRing",         "VR1_D",         
                                     "MPC7",           "MPC6",           "MWC10",          "MWC8",         "C4SP3",         
                                     "SRW10",          "TSRW",           "MWC4",           "nF10Ring",       "nT10Ring",      
                                     "GGI4",           "nF9Ring",        "nT9Ring",        "WPOL",           "nRing",         
                                     "TIC2",           "GATS4p",         "GGI2",           "JGI8",           "ATSC4p",        
                                     "ATS5v",          "ATS1v",          "SRW9",           "SpDiam_Dt",      "ATS1p",         
                                     "ATSC0v",         "ATS6i",          "nBonds2",        "SIC5",           "TWC",           
                                     "CIC0",           "AATS2v",         "GGI6",           "GATS1i",         "CIC5",          
                                     "AATS2i",         "ATS3m",          "GGI3",           "apol",           "ATS1i",         
                                     "nAtom",          "Sp",             "JGI5",           "VR1_Dt",       "ATS0i",         
                                     "Si",             "Sv",             "ZMIC0",          "ATSC4m",         "nBonds",        
                                     "SRW2",           "ATS6v",          "nAtomP",         "ATS4m",          "nC",            
                                     "nH",             "SRW7",           "ATS7e",          "JGI7",           "ATS0v",        
                                     "ATS6p",          "ATS2m",          "JGI9",           "SIC3",           "IC2",           
                                     "MLogP",          "GGI5",           "ATS7i",          "ATSC0i",         "AATS2p",        
                                     "ATS5m",          "GGI7",         "ATS7p",          "McGowan_Volume", "AATS6p",        
                                     "n6Ring",         "nT6Ring",        "AATS1v",         "VE3_D",          "ATS0p",         
                                     "n5Ring",         "nT5Ring",       "ATS7v",          "AATS7p",         "GATS1p",        
                                     "TIC0",           "ATS8e",          "GGI9",           "GGI1",           "AATS7v",        
                                     "C2SP3",          "GGI8",           "SRW5",           "ECCEN",          "ATSC1v",        
                                     "CrippenMR",      "ATS8i",          "nHeavyAtom",     "VAdjMat",        "ATS1m",         
                                     "AATS8m",         "ATSC0p",         "VR2_D",          "ZMIC2",          "MW",            
                                     "R_TpiPCTPC",     "ZMIC1",          "AATS8v",         "AATS8p",         "JGI4",          
                                     "AATS4i",         "bpol",           "ATS7m",          "AATS7m",         "AATS6v",        
                                     "ATS6m",          "AATS6i",         "MATS7c",         "VR2_Dt",         "ATS8v",         
                                     "ATS8p",          "WPATH",          "MATS1c",         "MLFER_E",        "GATS6i",        
                                     "AATS7i",         "AATS0p",         "JGI2",           "MLFER_S",        "AATS8i",        
                                     "MATS5c",         "GATS8v",         "MLFER_L",        "ATS8m",          "piPC1",         
                                     "EE_D",           "SpAD_D",         "SpMax_D",        "MATS8e",         "AATS5m",        
                                     "SpDiam_D",       "Mv",             "GATS7v",         "MLFER_BO",       "GATS7p",        
                                     "ATSC1p",         "AATS3p",         "MATS1i",         "AATS5p",         "Mp",            
                                     "AATS4v",         "piPC3",         "JGT",            "GATS4m",         "piPC2",         
                                     "ATSC6i",         "AATS5v",         "AATSC1i",        "piPC8",          "AATS5i",        
                                     "piPC10",         "ATSC2v",         "MLFER_BH",       "piPC9",          "TpiPC",         
                                     "Kier1",          "piPC6",          "GATS8c",         "AATS6m",         "piPC7",         
                                     "ATSC6p",         "GATS4v",         "C2SP2",          "MATS8c",         "piPC4",         
                                     "ATSC2p",         "piPC5",          "MATS3c",         "ATSC0m",         "SpMAD_D",       
                                     "AATSC1v",        "MATS1v",         "SIC0",           "topoDiameter",   "BIC0",          
                                     "topoRadius",     "GATS4i",         "AATS8e",         "AATSC2p",        "MATS2p",        
                                     "ATS0m",          "GATS7c",         "GATS8e",         "ATSC5i",         "GATS7e",        
                                     "ATSC1i",         "ATSC2m",         "AATSC1p",        "AATSC2v",        "ATSC1m",        
                                     "ATSC6v",         "MIC5",           "MATS2v",         "MIC4",           "MATS2i",        
                                     "AATSC2i",        "GATS8i",         "JGI3",           "TopoPSA",        "JGI10",         
                                     "ATSC2i",         "ATSC5v",       "ATSC5p",         "MATS2m",         "MIC3",          
                                     "AATSC2m",        "RotBtFrac",      "MATS1p",         "AATS3i",         "GATS8p",        
                                     "AATS7e",         "CIC3"))

write.csv(data1, paste('media/',dirname,'/activityres.csv',sep=""),row.names = F)

